### ISSUE TITLE
The Voyage Process - Getting off to a Solid Start!

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier3-team-29#13]
**__Feature Description__**
Chingu has created a process for you to follow during the Voyage. This process helps you to get off on a solid start.

**__Major User Stories/tasks__**
- [ ] Step 1: 🤝 Meet your team & schedule Kickoff meeting #5 
- [ ] Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting #6 
- [ ] Step 3: 👍 Choose a project & create a Vision Statement #7 
- [ ] Step 4: 📤 Define & prioritize MVP features #8 
- [ ] Step 5: 📋 Create a Project Backlog #9 
- [ ] Step 6: 📝 Create a Low-fidelity wireframe #14 
- [ ] Step 7: ⚙️ Set Up a Team Workflow #10 

**__Additional Considerations__**
N/a
