### ISSUE TITLE
Getting Started: 🤔 Start thinking about project ideas & the technical stack

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier3-team-29#2]
**__Task Description__**
- [ ] Check out apps that Voyage teams have created in prior Voyage by reviewing the [Project Showcase](https://medium.com/chingu/chingu-fall-project-showcase-c6bf0f8210ab)
- [ ] Come up with 1 to 3 ideas for projects you'd like to build so you can discuss them with the rest of the team when the Voyage starts.
- [ ] Think about what technical stack you'd like to use to build that app. Similarly, you'll discuss this as a team at the start of the Voyage.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Choose a project & create a Vision Statement (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#fbb0adb051814a52a72675e1ef8b8b8d)

**Member of Epic:** #15
