### ISSUE TITLE
Step 1: 🤝 Meet your team & schedule Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier3-team-29#4]
**__Task Description__**
- [ ] Meet your team by adding your introduction to the Team Channel
- [ ] Start getting to know one another
- [ ] Start discussing what projects you would like to create
- [ ] Watch the [Voyage Team Roles](https://youtu.be/f_TzehtBliE) video to learn about the different roles members of your team may have signed up to fill.
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/f_TzehtBliE)
- [ ] Watch the [How to Select a Voyage Project](https://youtu.be/5Xv0C5VAKZc) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/5Xv0C5VAKZc)

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Meet Your team (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#4a1de1b3a0524c1aa2f629ee570460fd)

Use [When2Meet](https://when2meet.com) to identify days & times when everyone on the team is available to meet.

**Member of Epic:** #16
