### ISSUE TITLE
Step 4: 📤 Define & prioritize MVP features

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier3-team-29#7]
**__Task Description__**
- [ ] Each team member should add their ideas to the [Project Vision & Feature Planning template](https://docs.google.com/document/d/1hod0AJXVe1T9HDqSwLr6VGXBz0HJ-HG4aM8JKoeBB00/edit?usp=sharing) before the team meeting
- [ ] Prioritize each feature - _Must Have_, _Should Have_, _Nice to Have_
- [ ] Meet with the team to review each feature & refine priorities

**__Technical Considerations__**
N/a

**__Additional Considerations__**
All _Must Have_ tasks will make up your MVP. Make sure that you control the scope of the project by limiting the number of _Must Have_ features to the ones you can reasonably complete by the end of Sprint 6.

Remember that you can always add new features once you complete the MVP.

**__Resources__**
[Choose a Project & create a Vision Statement (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#fbb0adb051814a52a72675e1ef8b8b8d)
[Define & Prioritize MVP features (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#e4d54b93099d4d88a82e1c9dec705c51)

**Member of Epic:** #16
