### ISSUE TITLE
Step 5: 📋 Create a Project Backlog

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier3-team-29#8]
**__Task Description__**
- [ ] Watch the [How to Create a Project Backlog](https://youtu.be/FaoT-DTtXyA) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/FaoT-DTtXyA)
- [ ] Identify & prioritize features
- [ ] Create an epic for each feature
- [ ] Choose the highest priority epics & divide them into user stories
- [ ] Add your epics & user stories to a backlog tool. Due to it’s tight integration with GitHub we suggest using ZenHub (it’s free for teams using public repositories)
- [ ] Prioritize the user stories

**__Technical Considerations__**
N/a

**__Additional Considerations__**
During the Voyage you’ll refine the Project Backlog and in every Sprint you’ll move tasks from it to the Sprint Backlog. This is part of the Agile process helps you and your team concentrate only on the tasks that must be completed in that Sprint.

If you are using ZenHub don't forget you'll need to install its [browser extension](https://www.zenhub.com/extension) before you can see the ZenHub tab in your GitHub repo.

**__Resources__**
[Create a Project Backlog (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#dddba7ebc23644b3ae015c329f34eead)

**Member of Epic:** #16
