### ISSUE TITLE
Step 7: ⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier3-team-29#9]
**__Task Description__**
- [ ] Decide on the coding standards the team must follow.
- [ ] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [ ] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [ ] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [ ] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Reaching your MVP](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#f6be98f386854bab9f9b4da7f13e3ea3) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#04c66351937d48b589d835164a4ca0d5)
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://chingucohorts.notion.site/Git-Workflow-d5fba28e1d3043e1910b7d2eb8999793)
[Git Branches (Chingu Handbook)](https://chingucohorts.notion.site/Git-Branches-7ccbd0a34e1c4b87af583e3760632727)
[Git Commits (Chingu Handbook)](https://chingucohorts.notion.site/Git-Commits-6334daca89f840f381ee1e57243091ad)
[Git Pull Requests (Chingu Handbook)](https://chingucohorts.notion.site/Git-Pull-Requests-6eeda3f9342941ef9a06d1057f0b87a6)

**Member of Epic:** #16
